# Google App Engine configuration (alternative to Cloud Run)
runtime: python311

# Instance configuration
automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.6

# Resource configuration
resources:
  cpu: 2
  memory_gb: 2

# Environment variables
env_variables:
  STREAMLIT_SERVER_HEADLESS: "true"
  STREAMLIT_SERVER_PORT: "8080"
  STREAMLIT_SERVER_ADDRESS: "0.0.0.0"

# Health check
readiness_check:
  path: "/_stcore/health"
  check_interval_sec: 30
  timeout_sec: 10
  failure_threshold: 3

liveness_check:
  path: "/_stcore/health"
  check_interval_sec: 30
  timeout_sec: 10
  failure_threshold: 3

# Handlers
handlers:
- url: /.*
  script: auto
